I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter6.rpy", line 44, in script
    python:
  File "game/chapter6.rpy", line 58, in <module>
    renpy.jump(bad_ending)
NameError: name 'bad_ending' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter6.rpy", line 44, in script
    python:
  File "F:\Diogenes\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\Diogenes\RenPy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/chapter6.rpy", line 58, in <module>
    renpy.jump(bad_ending)
NameError: name 'bad_ending' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Miranda Game 1.0
Wed Apr 10 23:11:15 2024
